export const itemDatabase = {
  "101": { name: "Laptop", companyName: "Dell" },
  "102": { name: "Phone", companyName: "Samsung" },
  "103": { name: "Printer", companyName: "HP" },
  "104": { name: "Tablet", companyName: "Apple" },
  "105": { name: "Monitor", companyName: "LG" },
  "106": { name: "Keyboard", companyName: "Logitech" },
  "107": { name: "Mouse", companyName: "Razer" },
  "108": { name: "Smartwatch", companyName: "Garmin" },
  "109": { name: "Headphones", companyName: "Sony" },
  "110": { name: "Speakers", companyName: "Bose" },
  "111": { name: "External HDD", companyName: "Seagate" },
  "112": { name: "USB Flash Drive", companyName: "SanDisk" },
  "113": { name: "Router", companyName: "TP-Link" },
  "114": { name: "Power Bank", companyName: "Anker" },
  "115": { name: "Graphics Card", companyName: "NVIDIA" },
  "116": { name: "Processor", companyName: "Intel" },
  "117": { name: "Motherboard", companyName: "ASUS" },
  "118": { name: "RAM", companyName: "Corsair" },
  "119": { name: "SSD", companyName: "Western Digital" },
  "120": { name: "Cooling Fan", companyName: "Cooler Master" }
  };